### ISSUE TITLE
Still doesnt save colours?

### ISSUE THREAD

**Issue by FrezZyyyx** [NanoAi/gm_apg#42] opened 2020-04-05 03:38 UTC
what did u do exactly to try to fix it? cause i just recently updated to newest version of apg and advanced dupe 2 and its still has same issue. i paid someone to add a fix for it and it worked but i wanna use the most up to date versions of apg and advanced dupe 2 so. this is what the guy said when i asked what he did to fix it.

![image](https://user-images.githubusercontent.com/47873987/78466281-47185c80-76f7-11ea-8e7b-96c5a40d95ba.png)

**Comment by thegrb93** [comment] 2020-04-05 08:57
You can try deleting
https://github.com/NanoAi/gm_apg/blob/70da0df550939698b5ec16e0b817372dcc68bcdc/lua/apg/modules/ghosting.lua#L45-L67 and
https://github.com/NanoAi/gm_apg/blob/70da0df550939698b5ec16e0b817372dcc68bcdc/lua/apg/modules/ghosting.lua#L158 and
https://github.com/NanoAi/gm_apg/blob/70da0df550939698b5ec16e0b817372dcc68bcdc/lua/apg/modules/ghosting.lua#L198

And see if it works after that.

**Comment by FrezZyyyx** [comment] 2020-04-05 16:54
will try it

**Comment by AvarianKnight** [comment] 2020-04-06 04:30
You should be able to turn ghostColorToggle ("Enable Color" under Ghosting) and it will prevent colors from changing. This was the fix that was made but it is not forced off by default.

**Comment by NanoAi** [comment] 2020-04-06 23:53
Please try out the settings with the latest version, and let me know if it's fixed. @FrezZyyyx 
https://github.com/NanoAi/gm_apg/commit/9029932b6e73c8dc2be1d43b0ecaa9280cd9910e#diff-80879291e1a242b387cfc0bf4700abc5L48

**Comment by thegrb93** [comment] 2020-04-07 02:55
That was a bug for sure, but I don't think that's the problem. The problem is APG_oldColor is assigned before advdupe2 can assign a color, so after the APG_oldColor is reverted, the prop just loses its color.

**Comment by NanoAi** [comment] 2020-04-07 07:58
> That was a bug for sure, but I don't think that's the problem. The problem is APG_oldColor is assigned before advdupe2 can assign a color, so after the APG_oldColor is reverted, the prop just loses its color.

Yeah I suggested just grabbing the colour data from `duplicator.DoGeneric` as I'm sure the correct colour will be in there. https://github.com/NanoAi/gm_apg/issues/44

This should then updated the stored information and restore the correct colours when unghosting.

**Comment by FrezZyyyx** [comment] 2020-04-07 09:41
ill dl the new version now

**Comment by FrezZyyyx** [comment] 2020-04-08 14:15
so you fixed this yourself in the newest version yes?

**Comment by NanoAi** [comment] 2020-05-02 06:08
Assumed fixed.

**Closed as completed** 2020-05-02 06:08 UTC
